use std::{env, error::Error, fs, path::PathBuf};

#[path = "src/generation/mod.rs"]
mod generation;

// ======================================================================
// CONST

const CRATE_NAME: &str = "reed_solomon_simd";

// ======================================================================
// MAIN

fn main() -> Result<(), Box<dyn Error>> {
    println!("cargo:rerun-if-changed=README.md");
    println!("cargo:rerun-if-changed=src/generation");
    println!("cargo:rerun-if-changed=src/constants.rs");

    // Rustdocify README
    fs::write(
        PathBuf::from(env::var("OUT_DIR")?).join("README-rustdocified.md"),
        readme_rustdocifier::rustdocify(
            &fs::read_to_string("README.md")?,
            &env::var("CARGO_PKG_NAME")?,
            Some(&env::var("CARGO_PKG_VERSION")?),
            Some(CRATE_NAME),
        )?,
    )?;

    // Generate lookup tables
    let out_dir = PathBuf::from(env::var("OUT_DIR")?);
    let mut source = String::new();
    source.push_str("// Auto-generated by build.rs — do not edit\n\n");
    source.push_str(&generation::tables::generate_exp_source());
    source.push_str(&generation::tables::generate_log_source());
    source.push_str(&generation::tables::generate_log_walsh_source());
    source.push_str(&generation::tables::generate_skew_source());
    source.push_str(&generation::tables::generate_mul16_source());
    source.push_str(&generation::tables::generate_mul128_source());

    fs::write(out_dir.join("generated_tables.rs"), source)?;

    Ok(())
}
